/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // ── Theme-adaptive (CSS variable) ──────────────────
        background:                 'rgb(var(--c-bg) / <alpha-value>)',
        surface:                    'rgb(var(--c-surface) / <alpha-value>)',
        'surface-container-lowest': 'rgb(var(--c-surf-lowest) / <alpha-value>)',
        'surface-container-low':    'rgb(var(--c-surf-low) / <alpha-value>)',
        'surface-container':        'rgb(var(--c-surf) / <alpha-value>)',
        'surface-container-high':   'rgb(var(--c-surf-high) / <alpha-value>)',
        'surface-container-highest':'rgb(var(--c-surf-highest) / <alpha-value>)',
        'on-surface':               'rgb(var(--c-on-surf) / <alpha-value>)',
        'on-surface-variant':       'rgb(var(--c-on-surf-var) / <alpha-value>)',
        outline:                    'rgb(var(--c-outline) / <alpha-value>)',
        'outline-variant':          'rgb(var(--c-outline-var) / <alpha-value>)',
        primary:                    'rgb(var(--c-primary) / <alpha-value>)',
        'on-primary':               'rgb(var(--c-on-primary) / <alpha-value>)',
        secondary:                  'rgb(var(--c-secondary) / <alpha-value>)',
        'on-secondary':             'rgb(var(--c-on-secondary) / <alpha-value>)',
        error:                      'rgb(var(--c-error) / <alpha-value>)',
        'on-error':                 'rgb(var(--c-on-error) / <alpha-value>)',
        'error-container':          'rgb(var(--c-err-container) / <alpha-value>)',
        'on-error-container':       'rgb(var(--c-on-err-container) / <alpha-value>)',
        success:                    'rgb(var(--c-success) / <alpha-value>)',
        sidebar:                    '#0f1729',
        // ── Static design-system tokens ────────────────────
        'surface-bright':            '#f9f9ff',
        'surface-dim':               '#d3daea',
        'surface-variant':           '#dce2f3',
        'surface-tint':              '#4d44e3',
        'inverse-surface':           '#2a313d',
        'inverse-on-surface':        '#ebf1ff',
        'inverse-primary':           '#c3c0ff',
        'on-background':             '#151c27',
        'primary-container':         '#4f46e5',
        'on-primary-container':      '#dad7ff',
        'primary-fixed':             '#e2dfff',
        'primary-fixed-dim':         '#c3c0ff',
        'on-primary-fixed':          '#0f0069',
        'on-primary-fixed-variant':  '#3323cc',
        'secondary-container':       '#e1e3e4',
        'on-secondary-container':    '#626566',
        'secondary-fixed':           '#e1e3e4',
        'secondary-fixed-dim':       '#c5c7c8',
        'on-secondary-fixed':        '#191c1d',
        'on-secondary-fixed-variant':'#454748',
        'tertiary':                  '#684000',
        'on-tertiary':               '#ffffff',
        'tertiary-container':        '#885500',
        'on-tertiary-container':     '#ffd4a4',
        'tertiary-fixed':            '#ffddb8',
        'tertiary-fixed-dim':        '#ffb95f',
        'on-tertiary-fixed':         '#2a1700',
        'on-tertiary-fixed-variant': '#653e00',
      },
      borderRadius: {
        sm:      '0.25rem',   //  4px
        DEFAULT: '0.5rem',    //  8px
        md:      '0.75rem',   // 12px
        lg:      '1rem',      // 16px
        xl:      '1.5rem',    // 24px
        full:    '9999px',
      },
      fontFamily: {
        sans: ['Lato', 'Inter', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'],
      },
      fontSize: {
        'page-title':  ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-xl': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em',  fontWeight: '600' }],
        'headline-lg': ['20px', { lineHeight: '28px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-md': ['16px', { lineHeight: '24px', letterSpacing: '-0.01em',  fontWeight: '600' }],
        'headline-sm': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'body-lg':     ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md':     ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm':     ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-md':    ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-sm':    ['11px', { lineHeight: '14px', letterSpacing: '0.03em', fontWeight: '600' }],
        'label-xs':    ['10px', { lineHeight: '13px', letterSpacing: '0.04em', fontWeight: '600' }],
        // Icon sizes for material-symbols-outlined
        'icon-2xs':  '13px',
        'icon-xs':   '12px',
        'icon-sm':   '15px',
        'icon-base': '16px',
        'icon-md':   '18px',
        'icon-lg':   '20px',
        'icon-xl':   '22px',
        'icon-2xl':  '24px',
        'icon-3xl':  '28px',
        'icon-4xl':  '32px',
        'icon-5xl':  '40px',
        'icon-6xl':  '48px',
      },
      spacing: {
        base:            '4px',
        xs:              '8px',
        sm:              '12px',
        md:              '16px',
        lg:              '24px',
        xl:              '32px',
        gutter:          '16px',
        'margin-mobile': '16px',
        'margin-desktop':'32px',
        'sidebar-w':     '260px',
        kanban:          '300px',
        '5.5':           '22px',
        '0.75':          '3px',
        '1.25':          '5px',
        accent:          '3px',
        chart:           '140px',
        'chart-bar':     '110px',
      },
      zIndex: {
        modal: '100',
      },
    },
  },
  plugins: [],
}
